backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
site_url: "https://affectionate-kirch-0533c4.netlify.com/"
media_folder: "src/images"
public_folder: "images"
collections:

  - label: "Globals"
    name: "globals"
    files:
      # - label: "Site Data"
      #   name: "site_data"
      #   delete: false
      #   file: "src/_data/site.json"
      #   fields:
      #     - {label: "Site Name", name: "name", widget: "string"}
      #     - {label: "Site Url", name: "url", widget: "string"}
      #     - {label: "Author Name", name: "authorName", widget: "string"}
      #     - {label: "Author Email Address", name: "authorEmail", widget: "string"}
      #     - {label: "Author Twitter Handle", name: "authorHandle", widget: "string", required: false}
      #     - {label: "Footer Short Description", name: "shortDesc", widget: "string"}
      #     - {label: "Maximum Posts Per Page", name: "maxPostsPerPage", widget: "number", default: 5}
      #     - {label: "Show Theme Credit", name: "showThemeCredit", widget: "boolean", default: true}
      #     - {label: "Enable Third Party Comments Area", name: "enableThirdPartyComments", widget: "boolean", default: false}
      #     - {label: "Payment Pointer (Web Monetization: https://bit.ly/2kTRI1b)", name: "paymentPointer", widget: "string"}
      #     - {label: "Favicon path (EG: /images/favicon.png)", name: "faviconPath", widget: "string"}
      - label: "Header"
        name: "header"
        delete: false
        file: "src/_data/header.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
      - label: "teaching"
        name: "teaching"
        delete: false
        file: "src/_data/teaching.json"
        fields:
          - label: "mainText"
            name: "mainText"
            widget: string
          - label: "secondaryText"
            name: "secondaryText"
            widget: string
      - label: "Navigation"
        name: "nav"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Is url to external site?", name: "external", widget: "boolean", required: false}
      - label: "Fiction"
        name: "fiction"
        delete: false
        file: "src/_data/fiction.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "src", name: "src", widget: "image"}
              - {label: "link", name: "text", widget: "boolean", required: false}
          - label: "Headline"
            name: 'headline'
            widget: string
      - label: "NFE"
        name: "NFE"
        delete: false
        file: "src/_data/NFE.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "summary", name: "summary", widget: "string"}
              - {label: "details", name: "details", widget: "string", required: false}
              - {label: "link", name: "link", widget: "string", required: false}
              - {label: "src", name: "src", widget: "image", , required: false}
              - {label: "image2src", name: "image2src", widget: "image", required: false}
              - {label: "additionalText", name: "additionalText", widget: "string", required: false}
          - label: "Headline"
            name: 'headline'
            widget: string
      - label: "NFH"
        name: "NFH"
        delete: false
        file: "src/_data/NFH.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "summary", name: "summary", widget: "string"}
              - {label: "details", name: "details", widget: "string", required: false}
              - {label: "link", name: "link", widget: "string", required: false}
              - {label: "src", name: "src", widget: "image", , required: false}
              - {label: "image2src", name: "image2src", widget: "image", , required: false}
              - {label: "additionalText", name: "additionalText", widget: "string", required: false}
      - label: "events"
        name: "events"
        delete: false
        file: "src/_data/events.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "topText", name: "topText", widget: "string"}
              - {label: "bottomText", name: "bottomText", widget: "string"}
              - {label: "isHebrew", name: "isHebrew", widget: "boolean", required: false}
              - {label: "link", name: "link", widget: "string", required: false}
              - {label: "imgSrc", name: "imgSrc", widget: "image", , required: false}
      - label: "press"
        name: "press"
        delete: false
        file: "src/_data/press.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "bottomText", name: "bottomText", widget: "string"}
              - {label: "quote", name: "quote", widget: "string"}
              - {label: "isHebrew", name: "isHebrew", widget: "boolean", required: false}
              - {label: "link", name: "link", widget: "string", required: false}
          - label: "interviews"
            name: "interviews"
            widget: "list"
            fields:
              - {label: "topText", name: "topText", widget: "string"}
              - {label: "bottomText", name: "bottomText", widget: "string", required: false}
              - {label: "audio", name: "audio", widget: "file", required: false}
              - {label: "link", name: "link", widget: "string", required: false}
      - label: "Theme Settings"
        name: "theme"
        delete: false
        file: "src/_data/tokens.json"
        fields:
          - label: "Size Scale"
            name: "size-scale"
            widget: "object"
            fields: 
              - {label: "Base Size", name: "base", widget: "string", default: "1rem"}
              - {label: "Ratio: 300", name: "300", widget: "string", default: "0.8rem"}
              - {label: "Ratio: 500", name: "500", widget: "string", default: "1.25rem"}
              - {label: "Ratio: 600", name: "600", widget: "string", default: "1.56rem"}
              - {label: "Ratio: 700", name: "700", widget: "string", default: "1.95rem"}
              - {label: "Ratio: 800", name: "800", widget: "string", default: "2.44rem"}
              - {label: "Ratio: 900", name: "900", widget: "string", default: "3.05rem"}
              - {label: "Max Size", name: "max", widget: "string", default: "4rem"}
          - label: "Colors"
            name: "colors"
            widget: "object"
            fields: 
              - {label: "Primary", name: "primary", widget: "string", default: "hsl(208, 57%, 21%)"}
              - {label: "Primary Shade (darker)", name: "primary-shade", widget: "string", default: "hsl(208, 56%, 14%)"}
              - {label: "Primary Glare (lighter)", name: "primary-glare", widget: "string", default: "hsl(207, 57%, 31%)"}
              - {label: "Highlight", name: "highlight", widget: "string", default: "hsl(42, 98%, 77%)"}
              - {label: "Light", name: "light", widget: "string", default: "hsl(0, 0%, 100%)"}
              - {label: "Mid", name: "mid", widget: "string", default: "hsl(0, 0%, 80%)"}
              - {label: "Dark", name: "dark", widget: "string", default: "hsl(0, 0%, 20%)"}
              - {label: "Slate", name: "slate", widget: "string", default: "hsl(0, 0%, 25%)"}
          - label: "Fonts"
            name: "fonts"
            widget: "hidden"
            default: { "base": "\"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'\"", "serif": "\"'Lora', serif\""}
